### PR TITLE
Modified accumulo access to only work with String and Unicode.

### LINKED ISSUE #88: Implementation does not match specification
In the process of developing [a Rust implementation of this specification](https://github.com/willmurnane/access-rs), I implemented [a check that the Rust implementation's behavior matches the Java code](https://github.com/willmurnane/access-rs/pull/3), and was surprised to find that the Java code does not implement what the ABNF says it does. Specifically, [the ABNF says](https://github.com/apache/accumulo-access/blob/main/SPECIFICATION.md) that access tokens include quoted strings composed of characters 0x20 and greater with a few exceptions, but the Java code accepts the characters 0x0 through 0x1f, as demonstrated by running this code:
```java
package test.access;
import org.apache.accumulo.access.AccessEvaluator;
import org.apache.accumulo.access.AccessExpression;
import org.apache.accumulo.access.Authorizations;
import org.apache.accumulo.access.IllegalAccessExpressionException;

public class Main {
    public static void main(String[] args) {
        for (char i = 0; i < 0x25; i++) {
            String s = String.format("\"%c\"", i);
            System.out.printf("Character 0x%02x %s -> ", (int)i, s);
            try {
                if (i == 0x22) {
                    System.out.printf("Double quote is illegal, skipping\n");
                }
                AccessExpression.of(s);
                System.out.printf(" %s", AccessExpression.of(s));
                System.out.printf(" %s", AccessEvaluator.of(Authorizations.of(String.format("%c", i))).canAccess(s));
                if (i < 0x20) {
                    System.out.printf("(expected failure)\n");
                } else {
                    System.out.printf("(expected success)\n");
                }
            } catch (IllegalAccessExpressionException iaee) {
                System.out.printf("%s Failed!\n", s);
            }
        }
    }
}
```

I'm not sure what the intended behavior is here, should the specification or the code be updated to match the other?

### PR DESCRIPTION
**Pull request by keith-turner**
This is still a work in progress, but its close to being complete. Modified the Accumulo Access code to only use String and unicode.  Made the following changes.

 * Removed all methods that take `byte[]` in the API
 * Removed the many static entry points in the API and replaced them w/ a single static entry point.
 * Reworked the internal code to operate on char instead of byte.
 * Limited authorizations to valid unicode characters that are not ISO control characters by default.  This is configurable though.

Realized it would be really nice if users could further limit authorizations to a smaller subset of characters while working on this.  The existing Accumulo Access APIs had a ton of static entry points and there was no one place that configurable behavior could be introduced .  That led to reworking the API to have a single entry point where configuration could  be applied instead of the many entry static points.  Currently this entry point only allows setting a configurable authorization validator, but it makes it easy to support future configuration.  This new single entry point is conceptually similar to how Gson works, it was inspired by that.

Still puzzling about how Accumulo might use this code or if that is possible.  Want to experiment w/ that some.

Have not yet run the benchmarks w/ these code changes.

fixes #88

### CODE REVIEW

**Comment by keith-turner** [comment]
> Do we still need the quoting and unquoting of terms in an AccessExpression if the goal is String and Unicode only?

Yeah still need them, the quoting allows using characters that are reserved for the language itself in auths.  Also allows the language to use new characters in the future that are also used in quoted expressions.

File: core/src/main/java/org/apache/accumulo/access/AccumuloAccess.java [hunk 1]
```diff
@@ -0,0 +1,225 @@
...
+import org.apache.accumulo.access.impl.BuilderImpl;
+
+/**
+ * The entry point into Accumulo Access to create access expressions, expression evaluators, and
+ * authorization sets.
+ *
+ * @see #builder()
+ * @since 1.0
+ */
+public interface AccumuloAccess {
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/access/AccumuloAccess.java]: I don't think we need "Accumulo" prefix on this object. While Accumulo is the containing project, I think this class could just be called "Access".

File: core/src/main/java/org/apache/accumulo/access/AccumuloAccess.java [hunk 2]
```diff
@@ -0,0 +1,225 @@
...
+
+  /**
+   * Quickly validates that an access expression is properly formed.
+   *
+   * @param expression a potential access expression that
+   * @throws InvalidAccessExpressionException if the given expression is not valid
+   * @throws InvalidAuthorizationException if the expression contains an invalid authorization
+   * @throws NullPointerException when the argument is null
+   */
+  void validate(String expression)
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/access/AccumuloAccess.java]: I'm not sure I like this here. I get the utility of having it to avoid the object allocation if you just want to quickly verify a bunch of expressions, but it feels out of place. This isn't really here to construct or use an object from this library... it's just kind of an extra utility method that allows users to evaluate their own data. But, I think what users really are asking if they were to use this method is "if I were to construct a new AccessExpression from this String, would it succeed?", and I think the only 100% reliable way to do that is to just create a new AccessExpression from this String, which kind of makes this method redundant.

File: core/src/main/java/org/apache/accumulo/access/AccumuloAccess.java [hunk 3]
```diff
@@ -0,0 +1,225 @@
...
+   * </tr>
+   * <tr>
+   * <td>A&amp;D</td>
+   * <td>False</td>
+   * <td>False</td>
+   * </tr>
+   *
+   * </table>
+   */
+  AccessEvaluator newEvaluator(Collection<Authorizations> authorizationSets);
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/access/AccumuloAccess.java]: If AccessEvaluator were a FunctionalInterface (which I think it can, and should, be), I think this basically becomes something like:

```java
AccessEvaluator aggregateEvaluator = expression -> authorizationsSets.stream().map(this::newEvaluator).allMatch(e -> e.canAccess(expression));

for (AccessExpression expression : allExpressionsToEvaluate) {
  if (aggregateEvaluator.canAccess(expression)) {
    // do whatever
  }
}
```

I think this is something a user can do themselves (using streams or traditional loops) if they had this use case. I think this is a useful example to document, but I don't think we need it in the main API entry point.

File: core/src/main/java/org/apache/accumulo/access/AccumuloAccess.java (hunk 1 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/access/AccumuloAccess.java]: Made that change in 778c9e483adb83c1e3eefa3cb824456f0b1dd2f6.  I wanted a shorted name for this class but was not sure what name to use.  `Access` seems good to me.

File: core/src/main/java/org/apache/accumulo/access/Access.java [hunk 4]
```diff
@@ -0,0 +1,225 @@
...
+   * tree is already available, then it would likely be faster to use it rather than call this
+   * method.
+   * </p>
+   *
+   * @throws InvalidAccessExpressionException when the expression is not valid.
+   * @throws InvalidAuthorizationException when the expression contains an authorization that is not
+   *         valid
+   * @throws NullPointerException when any argument is null
+   */
+  void findAuthorizations(String expression, Consumer<String> authorizationConsumer)
```
[the remark this answers is not in the document]
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/access/Access.java]: It would be nice to move this out of the root level interface, however if that is done then expression would be parsed twice to do the following.  

```java
Access access = ...;
access.newExpression("a|b|c").findAuthorizations(System.out::println);
```

It will parse once to validate when creating the AccessExpression and then again when calling findAuthorizations().

File: core/src/main/java/org/apache/accumulo/access/Access.java [hunk 5]
```diff
@@ -0,0 +1,225 @@
...
+
+  /**
+   * Quickly validates that an access expression is properly formed.
+   *
+   * @param expression a potential access expression that
+   * @throws InvalidAccessExpressionException if the given expression is not valid
+   * @throws InvalidAuthorizationException if the expression contains an invalid authorization
+   * @throws NullPointerException when the argument is null
+   */
+  void validate(String expression)
```
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/access/Access.java]: It is the same as calling newExpression, except it does not allocate an object.  So its an optimization.  Could remove it, it can be added later.    Also could rename it to `validateExpression()` which lines up w/ the `newExpression()` method.

File: core/src/main/java/org/apache/accumulo/access/Access.java [hunk 6]
```diff
@@ -0,0 +1,225 @@
...
+   * </tr>
+   * <tr>
+   * <td>A&amp;D</td>
+   * <td>False</td>
+   * <td>False</td>
+   * </tr>
+   *
+   * </table>
+   */
+  AccessEvaluator newEvaluator(Collection<Authorizations> authorizationSets);
```
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/access/Access.java]: > If AccessEvaluator were a FunctionalInterface

Could be tricky to achieve that because it could lead to forcing double parsing (once for validation and once of evaluation) depending on how its done.

File: core/src/main/java/org/apache/accumulo/access/Access.java (hunk 5 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/access/Access.java]: Renamed to `validateExpression` in 7a375938e4ea914b9f5c50ac0bd6de47589d2eda.  Plan to evaluate removal based on trying to use the changes in accumulo.  I believe this is used now in main, but not 100% sure.

File: core/src/main/java/org/apache/accumulo/access/Access.java [hunk 7]
```diff
@@ -0,0 +1,225 @@
...
+   *         valid
+   * @throws InvalidAccessExpressionException if the given expression is not valid
+   */
+  ParsedAccessExpression newParsedExpression(String expression)
+      throws InvalidAccessExpressionException, InvalidAuthorizationException;
+
+  /**
+   * @return a pre-allocated empty Authorizations object
+   */
+  Authorizations newAuthorizations();
```
[the remark this answers is not in the document]
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/access/Access.java]: Removed in 8331f6313fd6e8aa12cceb3d1b326743ac72316c

File: core/src/main/java/org/apache/accumulo/access/impl/AuthorizationsImpl.java [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+ * under the License.
+ */
+package org.apache.accumulo.access.impl;
+
+import java.util.Iterator;
+import java.util.Set;
+
+import org.apache.accumulo.access.Authorizations;
+
+public final class AuthorizationsImpl implements Authorizations {
```
Comment (dlmarion) [inline core/src/main/java/org/apache/accumulo/access/impl/AuthorizationsImpl.java]: I wonder if this could simplify the code? Records are implicitly `final` and it takes care of the `equals`, `hashcode` and `toString` methods.
```
  public record AuthorizationsImpl(Set<String> authorizations) implements Authorizations
```

File: core/src/main/java/org/apache/accumulo/access/impl/AccessEvaluatorImpl.java [hunk 9]
```diff
@@ -30,42 +29,56 @@
...
 
   /**
    * Create an AccessEvaluatorImpl using an Authorizer object
    */
-  public AccessEvaluatorImpl(Authorizer authorizationChecker) {
-    this.authorizedPredicate = auth -> authorizationChecker.isAuthorized(unescape(auth));
+  public AccessEvaluatorImpl(Authorizer authorizationChecker,
+      AuthorizationValidator authorizationValidator) {
+    this.authorizedPredicate = auth -> authorizationChecker.isAuthorized(auth.toString());
+    this.authorizationValidator = authorizationValidator;
```
Comment (dlmarion) [inline core/src/main/java/org/apache/accumulo/access/impl/AccessEvaluatorImpl.java]: Can the validator be null?

File: core/src/main/java/org/apache/accumulo/access/impl/AccessEvaluatorImpl.java [hunk 10]
```diff
@@ -143,20 +157,29 @@ public boolean canAccess(AccessExpression expression) {
...
 
-  boolean evaluate(byte[] accessExpression) throws InvalidAccessExpressionException {
-    var bytesWrapper = ParserEvaluator.lookupWrappers.get();
+  boolean evaluate(String accessExpression) throws InvalidAccessExpressionException {
+    var charsWrapper = ParserEvaluator.lookupWrappers.get();
     Predicate<Tokenizer.AuthorizationToken> atp = authToken -> {
-      bytesWrapper.set(authToken.data, authToken.start, authToken.len);
-      return authorizedPredicate.test(bytesWrapper);
+      var authorization = ParserEvaluator.unescape(authToken, charsWrapper);
+      if (!authorizationValidator.test(authorization, authToken.quoting)) {
```
Comment (dlmarion) [inline core/src/main/java/org/apache/accumulo/access/impl/AccessEvaluatorImpl.java]: This will throw an NPE if the validator is null.

File: core/src/main/java/org/apache/accumulo/access/impl/AccessExpressionImpl.java
Comment (dlmarion) [inline core/src/main/java/org/apache/accumulo/access/impl/AccessExpressionImpl.java]: I wonder if this can be a Record and if there is any benefit to it.

File: core/src/main/java/org/apache/accumulo/access/impl/AccessEvaluatorImpl.java (hunk 9 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/access/impl/AccessEvaluatorImpl.java]: It should not be, added test and checks in 6752d657d5a4e926784150575779e04b73edb8f5.  The checks for null are in the API entry point.

File: core/src/main/java/org/apache/accumulo/access/impl/AuthorizationsImpl.java (hunk 8 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/access/impl/AuthorizationsImpl.java]: made record in 55a0c263f3bc6d97bfa97cc6ed92d19e1f658806

File: core/src/main/java/org/apache/accumulo/access/impl/CharsWrapper.java [hunk 11]
```diff
@@ -18,46 +18,59 @@
...
-import static java.util.Objects.checkFromIndexSize;
-import static java.util.Objects.checkIndex;
-
 import java.util.Arrays;
+import java.util.Objects;
 
-public final class BytesWrapper implements Comparable<BytesWrapper> {
-
-  private byte[] data;
+public final class CharsWrapper implements CharSequence {
```
[the remark this answers is not in the document]
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/access/impl/CharsWrapper.java]: This class is mutable, so can not be a record.

File: core/src/main/java/org/apache/accumulo/access/impl/AccessExpressionImpl.java
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/access/impl/AccessExpressionImpl.java]: Not sure, it currently does not have equals(), hashCode(), or toString().  Also, it has a mutable field that is in atomic ref.  It could be a record, but the atomic ref feels like it goes against the spirit of a record.
